version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run: 
          name: Build Docker image
          command: docker build -t olukotunts/app .
      - run:
          name: Push Docker image to Docker Hub
          command: docker push olukotunts/app
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Pull Docker image from Docker Hub
          command: docker pull olukotunts/app
      - run:
          name: Tag Docker image
          command: docker tag olukotunts/app registry.heroku.com/name-button/web
      - run:
          name: Log in to Heroku Container Registry
          command: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Push Docker image to Heroku
          command: docker push registry.heroku.com/name-button/web
      - run:
          name: Install snap
          command: sudo apt-get update && sudo apt-get install snap
      - run:
          name: Install Heroku CLI
          command: sudo snap install --classic heroku
      - run:
          name: Deploy Docker image to Heroku
          command: heroku container:release --app name-button web
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build